[package]
name = "makepad-studio-component"
version = "0.1.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Makepad studio components"
license = "MIT"

[dependencies]

[dependencies.makepad-component]
path = "../../component"
version = "0.1"


