[package]
name = "makepad-id-macros"
version = "0.1.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Makepad live macros"
license = "MIT"

[lib]
proc-macro = true

[dependencies]


